### ISSUE TITLE
Wrong handling of abstract features at configuration editor

### ISSUE THREAD

**Issue by fbenduhn** [tthuem/FeatureIDE#31] opened 2013-11-13 17:09 UTC
If a configuration needs to select abstract undefined features it is always marked as invalid. See example.

Seave selections of abstract features.

**Comment by tthuem** [comment] 2015-01-21 17:34
When are you planning to merge this into the master? The commit fixing the issue is already more than 2 months old.

**Comment by skrieter** [comment] 2015-01-29 16:15
Fixed and merged into Master.

**Closed by skrieter** 2015-01-29 16:15 UTC
Labels: bug (minor), Configuration
