### ISSUE TITLE
 Features on first level of FM outline not shown if part of group

### ISSUE THREAD

**Issue by fbenduhn** [tthuem/FeatureIDE#152] opened 2014-10-15 09:39 UTC
If there is a or-group or alternative-group directily under the root feature, the collaboration outline should expand the corrsponding features instead of only the group symbol.

**Comment by pinnecke** [comment] 2015-05-04 18:46
Since a "or" or "alternative" group is a single item to a feature node, I removed this "empty" node and attached the "or" resp. "alternative" image to the children instead. Moreover I redraw the images of the feature model outline such that the overall appearance is more consistent. Hence, the feature model outline root got a "feature ide/feature product line" icon and the constraints part got new icons as well.

Below a before/after comparison.

**Before**

![bildschirmfoto 2015-05-04 um 15 51 24](https://cloud.githubusercontent.com/assets/3775170/7459603/696ac9aa-f29d-11e4-9ad7-8a6d09786e7f.png)

**After**

![bildschirmfoto 2015-05-04 um 20 35 56](https://cloud.githubusercontent.com/assets/3775170/7459612/722ee01c-f29d-11e4-9776-682e8f764a5a.png)

Please review and merge, remote branch **issue_152**.

**Comment by tthuem** [comment] 2015-05-08 12:04
I like the idea. Why do these icons look different now?

**Comment by pinnecke** [comment] 2015-05-16 20:45
Because I redesign them in order to look more "consistent" ;)

**Comment by pinnecke** [comment] 2015-06-01 16:08
Merged

**Comment by tthuem** [comment] 2015-06-01 16:20
Unfortunately, they are not consistent with the feature diagram anymore. That's rather unintuitive.

**Comment by pinnecke** [comment] 2015-06-01 19:43
But isn't it consistent with the advanced configuration editor? Moreover, it reduces the size of the tree. The current view is the result of a brainstorm between Raimer, Sebastian and me and "approved" by Fabian. We can revert this, but then the issue is back ("or/xor" nodes does not automatically elapse the sub tree; since SWT is a bit fuzzy here, it is more effort to solve this, otherwise).

**Comment by tthuem** [comment] 2015-06-02 08:22
I'm just irritated by the icon's design and not questioning the tree structure. Why can't you just take the old icons and design two new ones that look similar?

**Comment by pinnecke** [comment] 2015-06-03 15:52
Revert icons, please check and merge into master. Remote branch issue_152_fix

**Comment by tthuem** [comment] 2015-06-03 17:37
Thanks! If there is spare time, we can produce some icons for constraint that look similar to the existing ones.

**Closed by tthuem** 2015-06-03 17:37 UTC
Labels: enhancement, Feature Modeling
