### ISSUE TITLE
Fuji causes error for GameOfLife example

### ISSUE THREAD

**Issue by fbenduhn** [tthuem/FeatureIDE#120] opened 2014-09-18 10:25 UTC
The following exception is thrown when type checking the GameOfLife-FH-Java example:

java.lang.ArrayIndexOutOfBoundsException: 27493
	at AST.BytecodeParser.parseThisClass(BytecodeParser.java:440)
	at AST.BytecodeParser.parseTypeDecl(BytecodeParser.java:399)
...
	at fuji.Main.typecheckAST(Main.java:443)
	at de.ovgu.featureide.featurehouse.FeatureHouseComposer.runFuji(FeatureHouseComposer.java:704)
...

**Comment by tthuem** [comment] 2015-01-26 11:50
See #87 

We should check whether the problem occurs with the most recent version, after we got it.

**Comment by pinnecke** [comment] 2015-01-28 10:35
As I see it: This seems to be caused by #87 (beacuse it's the same exception). Fabian, I assume that you are using Java 1.8. Please **check it again with Java 1.7**, comment you results here and reassigne it to me when you're done.

**Comment by tthuem** [comment] 2015-02-02 07:34
Duplicate to #87

**Closed by tthuem** 2015-02-02 07:34 UTC
Labels: bug (critical), FeatureHouse
