### ISSUE TITLE
Constraints in feature diagram mistakenly declared as redundant

### ISSUE THREAD

**Issue by maxk11** [tthuem/FeatureIDE#230] opened 2015-03-18 12:30 UTC
The constraints in the feature diagramm are sometimes marked as redudant, even if not redundant.

Also, the feature diagramm does not update it's view. If a constraint is marked as redundant, it is not always colored yellow.

You can see both issues in this picture:
![redundant](https://cloud.githubusercontent.com/assets/7060562/6708698/fd78e35c-cd72-11e4-9b84-cddc2e98dffb.PNG)

**Comment by pinnecke** [comment] 2015-05-11 18:59
Seems to be caused by miss-caching in Feature Model Analyzer.

**Comment by pinnecke** [comment] 2015-05-16 20:38
Refactored feature model properties (such as it contains dead features) and set deprecated flag to old methods. Further: The legend now updates correctly the state. For at least false-optional constraints, the feature model is colored entirely which might be wrong.

![bildschirmfoto 2015-05-16 um 22 36 25](https://cloud.githubusercontent.com/assets/3775170/7667867/435c8432-fc1c-11e4-8f12-5887733afa13.png)

**Comment by pinnecke** [comment] 2015-05-16 20:39
Still open: <code>FeatureDiagramEditor</code> does not update the colors correctly. When changing the layout state (or closing, re-opening the model) everything is fine.

**Comment by pinnecke** [comment] 2015-06-08 22:31
The legend figure does not update correctly from time to time. Using bisect I found that commit 8ca0bed58ca4eb2a80760748534757317666dc13 introduces this in LegendFigure.java. To solve the display issue, I revert this file to the content before this commit. Since this commit focused on certain performance improvements, this revert might slow down the performance to the state before the changes.

**Comment by pinnecke** [comment] 2015-06-08 22:32
To my mind, constraints in feature diagram does not mistakenly declared as redundant anymore. Please check, comment and re-assign to me.

**Comment by tthuem** [comment] 2015-06-09 08:25
No one is assigned for review so far.

**Comment by skrieter** [comment] 2015-06-12 12:16
Fixed the main problem.
A small issue remains, regarding the legend (See #266).

**Closed by skrieter** 2015-06-12 12:16 UTC
Labels: bug (major), Feature Modeling, In review

**Comment by pinnecke** [comment] 2015-07-01 17:20
What's with the remote branch? Can it be removed?
