### ISSUE TITLE
Add feature name to tooltip in FeatureModel editor

### ISSUE THREAD

**Issue by meinicke** [tthuem/FeatureIDE#261] opened 2015-06-03 11:26 UTC
When zooming out it is no longer possible to read the names of the feautres, thus it may be helpfull to see the name at the tooltip

**Comment by pinnecke** [comment] 2015-06-09 13:04
See remote branch **issue_261**. Please comment and merge, if everything is okay. Please note: Due to using fixed fonts in FeatureIDE, there seems to be a font size issue when using OS X (which means, 8pt Fonts are too small).

Here is how it now looks on OS X/Eclipse:

![bildschirmfoto 2015-06-09 um 15 01 31](https://cloud.githubusercontent.com/assets/3775170/8058285/ae13d20e-0eb8-11e5-9a2e-f7f7a4b2ad66.png)

We should eventually investigate some time to fix the font size OS compatibility issue.

**Comment by meinicke** [comment] 2015-06-09 13:52
The tooltip (sometimes) does not display the corresponding constraint.
Do not set the feature name at a different line and with a bigger font.

![featuretooltip](https://cloud.githubusercontent.com/assets/1482595/8059268/4dfd2a8a-0ebf-11e5-980c-ed1c4e901097.png)

**Comment by meinicke** [comment] 2015-06-09 14:17
see: de.ovgu.featureide.fm.ui.editors.featuremodel.figures.FeatureFigure.setProperties()

**Comment by pinnecke** [comment] 2015-06-09 14:37
What exactly should be displayed in the tooltip? The feature name, I guess since this was in the description. 

When other infos should be displayed, please be clear about this. 

The bold/normal font was intended to distinguish between other tooltips inside the diagram.  

How to continue?

**Comment by meinicke** [comment] 2015-06-09 14:59
wtf?
the old content should still be displayed!
Just add the name of the feature

see: de.ovgu.featureide.fm.ui.editors.featuremodel.figures.FeatureFigure.setProperties()

**Comment by pinnecke** [comment] 2015-06-09 15:33
![bildschirmfoto 2015-06-09 um 17 32 53](https://cloud.githubusercontent.com/assets/3775170/8061965/919e090e-0ecd-11e5-89d5-9c573a0d6fce.png)

See remote branch **issue_261**. Please comment and merge, if everything is okay.

**Comment by pinnecke** [comment] 2015-06-10 15:05
Merged into master

**Comment by tthuem** [comment] 2015-06-10 18:27
So, we can close this issue?

**Comment by pinnecke** [comment] 2015-06-10 19:01
Yes, forgot this.
Am 10.06.2015 20:27 schrieb "Thomas Thüm" <notifications@github.com>:

**Closed** 2015-06-11 08:56 UTC
Labels: enhancement, Feature Modeling, In progress
