### ISSUE TITLE
Content assist of constraint dialog does not work anymore

### ISSUE THREAD

**Issue by tthuem** [tthuem/FeatureIDE#189] opened 2015-02-02 15:48 UTC
The content assist does never seem to allow the user to insert binary operators (e.g., implies):

![bug](https://cloud.githubusercontent.com/assets/5330357/6003336/32a0d8b8-aafb-11e4-9d84-c1b8a7abcc67.png)

**Comment by tthuem** [comment] 2015-02-04 08:55
Even worse, creating a constraint simply by clicking does not work anymore, too:

![syntax-bug](https://cloud.githubusercontent.com/assets/5330357/6037400/97a9856c-ac53-11e4-8e55-850c18b20b2a.png)

Clicking on a feature with white spaces needs to add " around the name to avoid syntax errors. I'm pretty sure that white spaces in feature names were supported in prior versions.

Also, we've had better error explanations than "there is a syntax error".

:(

**Comment by pinnecke** [comment] 2015-02-10 19:33
>The content assist does never seem to allow the user to insert binary operators (e.g., implies):

The proposal for the first feature *A* was matched as something where "not" is the only operator in proposal. This was caused by a *unhanded case* in which the word before the current word is empty (because the current word is the first word). I added this and now it works as expected. Of course this may lead to a case in which all the other operators are displayed where *not* should be displayed, but my tests didn't confirmed this problem, so I assume that everything is know all right. However, the fix is available in remote branch **issue_189**. Please check.

**Comment by pinnecke** [comment] 2015-02-10 19:49
Extracted the topic of Thomas 

> Even worse, creating a constraint simply by clicking does not work an ...

to new issue #210.

**Comment by pinnecke** [comment] 2015-02-10 19:50
Please check in remote branch **issue_189** if proposal now works as expected and reassign me if a result is clear.

**Comment by tthuem** [comment] 2015-02-10 21:49
Unfortunately, three tests in fm.ui-test fail. Please investigate them before I do the code review and manual testing.

**Comment by pinnecke** [comment] 2015-02-25 09:50
Merged into #210, please check this.

**Comment by tthuem** [comment] 2015-02-27 19:20
Seems to work. Please merge, when #210 is ready.

**Comment by pinnecke** [comment] 2015-02-28 19:39
Already merged into branch #210. Please note the following: 

> Unfortunately, three tests in fm.ui-test fail. Please investigate them before I do the code review and manual testing.

Because the context-senestive visibility of operators and features were buggy and we talked about moving it to software project (see #178), I removed the context-senestive visibility completely such that all operators and all features are visible independent from the context. Hence the tests in ``de.ovgu.featureide.fm.ui.editors.ConstraintContentProposalProviderTest``related to the content of the proposal in context of a given input will fail until the students implement this features again. The affected tests are commented-out by me it last commit of #210.

If you agree with this, you can close this issue because there is nothing to do here anymore.

**Closed** 2015-03-02 07:41 UTC
Labels: bug (minor), Feature Modeling
